REGIONS = [
      {"regionCode": 1, "regionName": "Крим"},
      {"regionCode": 2, "regionName": "Вiнницька"},
      {"regionCode": 3, "regionName": "Волинська"},
      {"regionCode": 4, "regionName": "Днiпропетровська"},
      {"regionCode": 5, "regionName": "Донецька"},
      {"regionCode": 6, "regionName": "Житомирська"},
      {"regionCode": 7, "regionName": "Закарпатська"},
      {"regionCode": 8, "regionName": "Запорiзька"},
      {"regionCode": 9, "regionName": "Iвано-Франкiвська"},
      {"regionCode": 10, "regionName": "Київська"},
      {"regionCode": 11, "regionName": "Кировоградська"},
      {"regionCode": 12, "regionName": "Луганська"},
      {"regionCode": 13, "regionName": "Львiвська"},
      {"regionCode": 14, "regionName": "Миколаївська"},
      {"regionCode": 15, "regionName": "Одеська"},
      {"regionCode": 16, "regionName": "Полтавська"},
      {"regionCode": 17, "regionName": "Рiвненська"},
      {"regionCode": 18, "regionName": "Сумська"},
      {"regionCode": 19, "regionName": "Тернопiльська"},
      {"regionCode": 20, "regionName": "Харкiвська"},
      {"regionCode": 21, "regionName": "Херсонська"},
      {"regionCode": 22, "regionName": "Хмельницька"},
      {"regionCode": 23, "regionName": "Черкаська"},
      {"regionCode": 24, "regionName": "Чернiвецька"},
      {"regionCode": 25, "regionName": "Чернiгiвська"},
      {"regionCode": 26, "regionName": "м.Київ"},
      {"regionCode": 27, "regionName": "м.Севастопiль"},
      {"regionCode": 28, "regionName": "Mik терр"},
      {"regionCode": 99, "regionName": "ДПА України"},
    ]
    